import React, { useCallback, useEffect, useMemo, useState } from "react";
import axios from "axios";
import { FaArrowDown, FaArrowUp, FaBalanceScale, FaBoxOpen, FaCalendarAlt, FaChartLine, FaChevronLeft, FaChevronRight, FaCoins, FaDownload, FaGem, FaRecycle, FaRupeeSign, FaSearch, FaSpinner, FaWarehouse, FaWeightHanging } from "react-icons/fa";
import BASE_URL from "./apiConfig";
import "./Profit.css";
const API=`${BASE_URL}/profit_loss_api.php`; const today=new Date().toISOString().slice(0,10); const monthStart=new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10); const money=v=>Number(v||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2}); const wt=v=>Number(v||0).toFixed(3);
export default function ProfitLoss(){
 const [metals,setMetals]=useState([]); const [filters,setFilters]=useState({from:monthStart,to:today,metal_id:"all",search:""}); const [summary,setSummary]=useState({sold:{},available:{},raw:{}}); const [daily,setDaily]=useState([]); const [metalSummary,setMetalSummary]=useState([]); const [soldRows,setSoldRows]=useState([]); const [stockRows,setStockRows]=useState([]); const [rawRows,setRawRows]=useState([]); const [soldPage,setSoldPage]=useState(1); const [stockPage,setStockPage]=useState(1); const [rawPage,setRawPage]=useState(1); const [soldPages,setSoldPages]=useState(1); const [stockPages,setStockPages]=useState(1); const [rawPages,setRawPages]=useState(1); const [activeTab,setActiveTab]=useState("sold"); const [loading,setLoading]=useState(false); const limit=10;
 const query=useCallback((action,page=1)=>`${API}?${new URLSearchParams({action,from:filters.from,to:filters.to,metal_id:filters.metal_id,search:filters.search,page,limit}).toString()}`,[filters]);
 const loadMasters=useCallback(async()=>{try{const r=await axios.get(`${API}?action=masters`); if(r.data.status==="success")setMetals(r.data.metals||[])}catch{}},[]);
 const loadAll=useCallback(async()=>{setLoading(true); try{const [sum,sold,stock,raw]=await Promise.all([axios.get(query("summary",1)),axios.get(query("sold_list",soldPage)),axios.get(query("available_stock",stockPage)),axios.get(query("raw_stock",rawPage))]); if(sum.data.status==="success"){setSummary(sum.data.summary||{sold:{},available:{},raw:{}}); setDaily(sum.data.daily||[]); setMetalSummary(sum.data.metal||[])} if(sold.data.status==="success"){setSoldRows(sold.data.data||[]); setSoldPages(sold.data.pagination?.pages||1)} if(stock.data.status==="success"){setStockRows(stock.data.data||[]); setStockPages(stock.data.pagination?.pages||1)} if(raw.data.status==="success"){setRawRows(raw.data.data||[]); setRawPages(raw.data.pagination?.pages||1)}} finally{setLoading(false)}},[query,soldPage,stockPage,rawPage]);
 useEffect(()=>{loadMasters()},[loadMasters]); useEffect(()=>{loadAll()},[loadAll]);
 const sold=summary.sold||{}, available=summary.available||{}, raw=summary.raw||{}; const profit=Number(sold.gross_profit||0); const updateFilter=(k,v)=>{setFilters(p=>({...p,[k]:v})); setSoldPage(1); setStockPage(1); setRawPage(1)};
 const maxDaily=Math.max(...daily.map(d=>Math.abs(Number(d.profit||0))),1);
 const exportCsv=()=>{const rows=activeTab==="sold"?soldRows:activeTab==="stock"?stockRows:rawRows; const headers=activeTab==="sold"?["Bill","Date","Barcode","Product","Customer","Sale","Cost","Profit"]:activeTab==="stock"?["Barcode","Product","Metal","Weight","Rate","Value"]:["Metal","Purity","Supplier","Weight","Rate","Value"]; const body=rows.map(r=>activeTab==="sold"?[r.bill_no,r.sale_date,r.barcode_no,r.product_name,r.customer_name,r.sale_amount,r.cost_amount,r.profit_amount]:activeTab==="stock"?[r.barcode_no,r.product_name,r.metal_name,r.remaining_weight,r.rate_per_gram,r.total_amount]:[r.metal_name,r.purity_name,r.firm_name,r.remaining_weight,r.rate_per_gram,r.total_value]); const csv=[headers,...body].map(a=>a.map(x=>`"${String(x??"").replace(/"/g,'""')}"`).join(',')).join('\n'); const blob=new Blob([csv],{type:'text/csv'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=`profit-loss-${activeTab}.csv`; a.click(); URL.revokeObjectURL(url)};
 return <div className="pl-page"><div className="pl-container"><header className="pl-hero"><div className="pl-hero-icon"><FaChartLine/></div><div><p>Jewellery Analytics</p><h1>Profit / Loss & Inventory Value</h1><span>Finished jewellery profit, remaining stock value and raw metal asset value.</span></div><button onClick={loadAll}><FaRecycle/> Refresh</button></header>
 <section className="pl-filters"><label><FaCalendarAlt/> From<input type="date" value={filters.from} onChange={e=>updateFilter('from',e.target.value)}/></label><label><FaCalendarAlt/> To<input type="date" value={filters.to} onChange={e=>updateFilter('to',e.target.value)}/></label><label><FaGem/> Metal<select value={filters.metal_id} onChange={e=>updateFilter('metal_id',e.target.value)}><option value="all">All Metals</option>{metals.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label className="search"><FaSearch/><input value={filters.search} onChange={e=>updateFilter('search',e.target.value)} placeholder="Search bill/barcode/product/supplier"/></label><button className="export" onClick={exportCsv}><FaDownload/> Export</button></section>
 <section className="pl-stats"><div className="stat"><FaRupeeSign/><span>Sales Value</span><b>₹{money(sold.sales_value)}</b><small>{sold.sold_items||0} sold items</small></div><div className="stat"><FaCoins/><span>Sold Stock Cost</span><b>₹{money(sold.cost_value)}</b><small>Exact barcode cost</small></div><div className={`stat ${profit>=0?'profit':'loss'}`}>{profit>=0?<FaArrowUp/>:<FaArrowDown/>}<span>{profit>=0?'Gross Profit':'Gross Loss'}</span><b>₹{money(Math.abs(profit))}</b><small>{money(sold.profit_percent)}%</small></div><div className="stat"><FaBoxOpen/><span>Finished Stock Value</span><b>₹{money(available.available_value)}</b><small>{available.available_items||0} items • {wt(available.available_weight)}g</small></div><div className="stat"><FaWarehouse/><span>Raw Metal Value</span><b>₹{money(raw.raw_value)}</b><small>{raw.raw_items||0} lots • {wt(raw.raw_weight)}g</small></div><div className="stat"><FaBalanceScale/><span>Total Inventory Asset</span><b>₹{money(available.total_inventory_value)}</b><small>Finished + Raw</small></div></section>
 <section className="pl-grid"><div className="pl-card chart-card"><div className="card-head"><h2>Daily Profit Trend</h2><span>{filters.from} to {filters.to}</span></div>{daily.length?<div className="bars">{daily.map(d=>{const val=Number(d.profit||0),h=Math.max(8,Math.abs(val)/maxDaily*120);return <div className="bar-item" key={d.sale_date}><div className={val>=0?'bar up':'bar down'} style={{height:`${h}px`}} title={`₹${money(val)}`}/><small>{d.sale_date.slice(5)}</small></div>})}</div>:<div className="empty">No sales in selected period</div>}</div><div className="pl-card metal-card"><div className="card-head"><h2>Metal-wise Profit</h2><FaBalanceScale/></div>{metalSummary.length?metalSummary.map(m=><div className="metal-row" key={m.metal_name}><div><b>{m.metal_name}</b><small>{m.sold_items} items</small></div><span className={Number(m.profit)>=0?'good':'bad'}>₹{money(m.profit)}</span></div>):<div className="empty">No metal summary</div>}</div></section>
 <section className="pl-card list-card"><div className="tab-head"><div className="tabs"><button className={activeTab==='sold'?'active':''} onClick={()=>setActiveTab('sold')}>Sold Profit/Loss</button><button className={activeTab==='stock'?'active':''} onClick={()=>setActiveTab('stock')}>Finished Stock</button><button className={activeTab==='raw'?'active':''} onClick={()=>setActiveTab('raw')}>Raw Metal Stock</button></div></div>
 {loading?<div className="loader"><FaSpinner className="spin"/> Loading...</div>: activeTab==='sold'?<TableSold rows={soldRows} page={soldPage} limit={limit}/>:activeTab==='stock'?<TableStock rows={stockRows} page={stockPage} limit={limit}/>:<TableRaw rows={rawRows} page={rawPage} limit={limit}/>}<div className="pager">{activeTab==='sold'?<Pager page={soldPage} pages={soldPages} setPage={setSoldPage}/>:activeTab==='stock'?<Pager page={stockPage} pages={stockPages} setPage={setStockPage}/>:<Pager page={rawPage} pages={rawPages} setPage={setRawPage}/>}</div></section></div></div>
}
function Pager({page,pages,setPage}){return <><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}><FaChevronLeft/></button><b>Page {page}/{pages||1}</b><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}><FaChevronRight/></button></>}
function TableSold({rows,page,limit}){return <div className="table-wrap"><table><thead><tr><th>#</th><th>Bill/Date</th><th>Barcode</th><th>Product</th><th>Customer</th><th>Sale</th><th>Cost</th><th>Profit</th></tr></thead><tbody>{rows.length?rows.map((r,idx)=><tr key={r.sale_item_id}><td>{(page-1)*limit+idx+1}</td><td><b>{r.bill_no}</b><small>{r.sale_date}</small></td><td>{r.barcode_no}</td><td><b>{r.product_name}</b><small>{r.metal_name} • {wt(r.net_weight)}g</small></td><td>{r.customer_name}</td><td>₹{money(r.sale_amount)}</td><td>₹{money(r.cost_amount)}</td><td><b className={Number(r.profit_amount)>=0?'good':'bad'}>₹{money(r.profit_amount)}</b><small>{money(r.profit_percent)}%</small></td></tr>):<tr><td colSpan="8" className="empty">No sold records</td></tr>}</tbody></table></div>}
function TableStock({rows,page,limit}){return <div className="table-wrap"><table><thead><tr><th>#</th><th>Barcode</th><th>Product</th><th>Metal</th><th>Wt</th><th>Rate</th><th>Making</th><th>Value</th></tr></thead><tbody>{rows.length?rows.map((r,idx)=><tr key={r.stock_id}><td>{(page-1)*limit+idx+1}</td><td>{r.barcode_no}</td><td><b>{r.product_name}</b><small>{r.batch_type}</small></td><td>{r.metal_name}</td><td>{wt(r.remaining_weight)}g</td><td>₹{money(r.rate_per_gram)}</td><td>₹{money(r.making_charge)}</td><td><b>₹{money(r.total_amount)}</b></td></tr>):<tr><td colSpan="8" className="empty">No finished stock</td></tr>}</tbody></table></div>}
function TableRaw({rows,page,limit}){return <div className="table-wrap"><table><thead><tr><th>#</th><th>Metal</th><th>Purity</th><th>Supplier</th><th>Date</th><th>Remaining Wt</th><th>Rate</th><th>Value</th></tr></thead><tbody>{rows.length?rows.map((r,idx)=><tr key={r.raw_stock_id}><td>{(page-1)*limit+idx+1}</td><td><b>{r.metal_name}</b></td><td>{r.purity_name||'-'}</td><td>{r.firm_name||'-'}</td><td>{r.purchase_date}</td><td>{wt(r.remaining_weight)}g</td><td>₹{money(r.rate_per_gram)}</td><td><b>₹{money(Number(r.remaining_weight||0)*Number(r.rate_per_gram||0))}</b></td></tr>):<tr><td colSpan="8" className="empty">No raw metal stock</td></tr>}</tbody></table></div>}
